version: "3"

services:
  storage:
    image: pgrouting/pgrouting:13-3.1-3.1.3
    container_name: "trailcatalog-postgres"
    restart: always
    environment:
      - POSTGRES_DB=trailcatalog
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./database/schema/tables.sql:/docker-entrypoint-initdb.d/tables.sql
    ports:
      - 5435:5432
