version: "3"

services:
  postgis:
    image: pgrouting/pgrouting:12-3.0-2.6.3
    container_name: "pgrouting-demo"
    restart: always
    environment:
      - POSTGRES_DB=trails
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./database/schema/tables.sql:/docker-entrypoint-initdb.d/tables.sql
      - db-data:/var/lib/postgresql/data
    ports:
      - 5435:5432

volumes:
  db-data:
